# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-10 10:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0009_slugfield_noop'),
        ('booking', '0002_auto_20170710_0917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availablerooms',
            name='product',
        ),
        migrations.AddField(
            model_name='booking',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalogue.Product'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AvailableRooms',
        ),
    ]
