# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-14 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0009_slugfield_noop'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='accomodation',
            field=models.TextField(blank=True, verbose_name='Accomodation'),
        ),
        migrations.AddField(
            model_name='product',
            name='activities',
            field=models.TextField(blank=True, verbose_name='Activities'),
        ),
        migrations.AddField(
            model_name='product',
            name='the_experience',
            field=models.TextField(blank=True, verbose_name='The Experience'),
        ),
    ]
